s/K7H.hybrid.assembly.contigs.fasta/URI42H.fasta/g
s/K60H.hybrid.assembly.contigs.fasta/URI87H.fasta/g
s/K25H.hybrid.assembly.contigs.fasta/URI36H.fasta/g
s/K71H.hybrid.assembly.contigs.fasta/URI91H.fasta/g
s/K11H.hybrid.assembly.contigs.fasta/UCT30H.fasta/g
s/K22H.hybrid.assembly.contigs.fasta/URI34H.fasta/g
s/K19H.hybrid.assembly.contigs.fasta/URI48H.fasta/g
s/K76H.hybrid.assembly.contigs.fasta/UCT113H.fasta/g
s/K16H.hybrid.assembly.contigs.fasta/URI33H.fasta/g
s/K82H.hybrid.assembly.contigs.fasta/URI117H.fasta/g
s/K10H.hybrid.assembly.contigs.fasta/UCT31H.fasta/g
s/K84H.hybrid.assembly.contigs.fasta/UCT96H.fasta/g
s/K70H.hybrid.assembly.contigs.fasta/UCT110H.fasta/g
s/K24H.hybrid.assembly.contigs.fasta/UCT35H.fasta/g
s/K6H.hybrid.assembly.contigs.fasta/URI41H.fasta/g
s/K17H.hybrid.assembly.contigs.fasta/URI46H.fasta/g
s/K83H.hybrid.assembly.contigs.fasta/URI118H.fasta/g
s/K69H.hybrid.assembly.contigs.fasta/UCT109H.fasta/g
s/EU14_B89613H.hybrid.assembly.contigs.fasta/ESI403H.fasta/g
s/L113H.hybrid.assembly.contigs.fasta/ESI425H.fasta/g
s/K18H.hybrid.assembly.contigs.fasta/URI47H.fasta/g
s/K1H.hybrid.assembly.contigs.fasta/UCT29H.fasta/g
s/K66H.hybrid.assembly.contigs.fasta/URI107H.fasta/g
s/K80H.hybrid.assembly.contigs.fasta/UCT95H.fasta/g
s/K74H.hybrid.assembly.contigs.fasta/URI111H.fasta/g
s/K2H.hybrid.assembly.contigs.fasta/URI39H.fasta/g
s/K13H.hybrid.assembly.contigs.fasta/URI45H.fasta/g
s/K56H.hybrid.assembly.contigs.fasta/URI86H.fasta/g
s/K73H.hybrid.assembly.contigs.fasta/URI93H.fasta/g
s/K59H.hybrid.assembly.contigs.fasta/URI103H.fasta/g
s/EU57_B190413H.hybrid.assembly.contigs.fasta/ESI26H.fasta/g
s/K62H.hybrid.assembly.contigs.fasta/URI88H.fasta/g
s/K3H.hybrid.assembly.contigs.fasta/URI40H.fasta/g
s/K64H.hybrid.assembly.contigs.fasta/URI89H.fasta/g
s/K21H.hybrid.assembly.contigs.fasta/UCT50H.fasta/g
s/K90H.hybrid.assembly.contigs.fasta/UCT124H.fasta/g
s/XD1H.hybrid.assembly.contigs.fasta/XYZ459H.fasta/g
s/EU51_B192411H.hybrid.assembly.contigs.fasta/ESI361.fasta/g
s/K30H.hybrid.assembly.contigs.fasta/URI56H.fasta/g
s/K75H.hybrid.assembly.contigs.fasta/URI112H.fasta/g
s/K15H.hybrid.assembly.contigs.fasta/UCT32H.fasta/g
s/K89H.hybrid.assembly.contigs.fasta/K89H.fasta/g
s/K58H.hybrid.assembly.contigs.fasta/URI102H.fasta/g
s/K72H.hybrid.assembly.contigs.fasta/UCT92H.fasta/g
s/K86H.hybrid.assembly.contigs.fasta/URI120H.fasta/g
s/K12H.hybrid.assembly.contigs.fasta/URI44H.fasta/g
s/K57H.hybrid.assembly.contigs.fasta/URI101H.fasta/g
